# Generated by Django 4.0.6 on 2022-07-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hailidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades Empleados',
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['lastName', 'firstName'], 'verbose_name': 'El empleado', 'verbose_name_plural': 'Los empleados'},
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('firstName', 'lastName')},
        ),
    ]
