# Generated by Django 4.0.6 on 2022-07-21 19:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_rename_hailidad_habilidades_habilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hojaVida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
    ]
