# Generated by Django 4.0.6 on 2022-07-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_empleado_hojavida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fullname',
            field=models.CharField(blank=True, max_length=260, verbose_name='Nombres Completos, '),
        ),
    ]
